version: '3.7'

services:
  web:
    container_name: restaurant-system-frontend
    build: .
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3030:3030'
    environment:
      - NODE_ENV=development
      - PORT=3030
    command: bash -c 'npm install && npm start'
